---
abstract: 'Create PDFs from a simple box markup language.'
author:
  - 'Jason Galea <lecstor@cpan.org>'
build_requires:
  DDP: 0
  Data::Dumper: 0
  File::Slurp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDF-Boxer
requires:
  Carp: 0
  Moose: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  PDF::API2: 0
  Scalar::Util: 0
  Try::Tiny: 0
  XML::Parser: 0
  namespace::autoclean: 0
version: 0.003
